name: Monaco Angular PR

on:
  pull_request:
    branches:
      - master
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "pkg/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.3.0
        with:
          node-version: "24.x"
          node-version-file: "package.json"
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm --filter sandbox exec playwright install --with-deps chromium
      - run: pnpm test