name: Monaco Angular PR

on:
  pull_request:
    branches:
      - master
    paths:
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "pkg/**/*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.4.0
        with:
          node-version: "20.x"
          node-version-file: "package.json"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm --filter sandbox exec playwright install --with-deps chromium
      - run: pnpm test