name: Monaco Angular PR (Skip)

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "pkg/**/*"
      - "pkg/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No relevant files changed, skipping."